### ISSUE TITLE
(IA) Funcionalidades do Bot

### ISSUE THREAD

**Issue by losout0** [Samurai-Turtles/Carta-Ninja#1]
Pesquisar como utilizar as informações das partidas anteriores para deixar o bot mais inteligente, tentado prever qual o padrão de comportamento do usuário.

**Comment by LucasKhalil** [comment]
O bot já é capaz de fazer escolhas inteligentes baseando-se na quantidade de cartas de cada tipo que o jogador tem, mas nada além disso.
