### ISSUE TITLE
(Core): Implementação do GameState

### ISSUE THREAD

**Issue by dougdomingos** [Samurai-Turtles/Carta-Ninja#2]
Definir, implementar e documentar o `GameState` do jogo.

O `GameState` é um conjunto de dados relacionados ao estado atual do jogo, incluindo coisas como:
- Modo (ou tela) em que o jogador se encontra
- Vida, cartas dos jogadores e outros fatores da Gameplay

Esse conjunto de dados é especialmente importante para que a interface esteja sincronizada com o estado atual do jogo.

**Comment by sergio-gustavo-andrade-grilo** [comment]
É necessário trocar a implementação das funções que manipulam JSONs e CSVs no GameState por funções IO, pois com elas é possível alterar o estado dos bancos de dados em arquivos em tempo de execução.
