### ISSUE TITLE
(UI) Decidir as dimensões da tela

### ISSUE THREAD

**Issue by sergio-gustavo-andrade-grilo** [Samurai-Turtles/Carta-Ninja#3]
As dimensões da tela são informações importantes, pois impactam diretamente no espaço que poderá ser utilizado pelos elementos da interface gráfica, como HUDs e Sprites em arte ASCII. Como a tarefa não demanda muito tempo, ela foi classificada como tamanho XS, mas ela ainda é muito importante.

**Comment by JWillianSl** [comment]
* Quantidades máximas de caracteres para compor a tela: 
 * 150 x 32 (caracteres) — tamanho hábil;
 * tamanho base terminal (Ideal), 168 x 35.
